#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker001"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "64a4f10238fb48c7a26d5ced0dc50d9b" }
]

[assets]
directory = "./public"
